

rm(list = ls())
library(R.matlab)
library(latex2exp)

Nall =c(100,200,400, 800, 1600, 3200)
error1all = rep(0, length(Nall)*5)
dim(error1all) = c(length(Nall), 5)
error2all = rep(0, length(Nall)*5)
dim(error2all) = c(length(cNall), 5)
error3all = rep(0, length(Nall)*5)
dim(error3all) = c(length(Nall), 5)
testerrorall = rep(0, length(Nall)*5)
dim(testerrorall) = c(length(Nall), 5)
timecostall = rep(0, length(Nall)*5)
dim(timecostall) = c(length(Nall), 5)


for(i in 1:length(Nall)){
  n = Nall[i]
  data = readMat(sprintf("./results/l2result_%d_sparse.mat",n))
  error1all[i,1] = mean(data$error1)
  error2all[i,1] = mean(data$error2)
  error3all[i,1] = mean(data$error3)
  testerrorall[i,1] = mean(data$testerror)
  timecostall[i,1] = mean(data$timerecord)
  load(sprintf("./results/l1result_%d_sparse.RData",n))
  error1all[i,2] = mean(df$error1)
  error2all[i,2] = mean(df$error2)
  error3all[i,2] = mean(df$error3)
  testerrorall[i,2] = mean(df$testerror)
  timecostall[i,2] = mean(df$timerecord)
  if (!(n %in% c(3200))){
    load(sprintf("./results/l0result_%d_sparse.RData",n))
    error1all[i,3] = mean(df$error1)
    error2all[i,3] = mean(df$error2)
    error3all[i,3] = mean(df$error3)
    testerrorall[i,3] = mean(df$testerror)
    timecostall[i,3] = mean(df$timerecord)
  }
  data = readMat(sprintf("./results/l2result_%d_sparse_5.mat",n))
  error1all[i,4] = mean(data$error1)
  error2all[i,4] = mean(data$error2)
  error3all[i,4] = mean(data$error3)
  testerrorall[i,4] = mean(data$testerror)
  timecostall[i,4] = mean(data$timerecord)
  data = readMat(sprintf("./results/l2result_%d_sparse_%d.mat",n,floor(n*log(n))
  error1all[i,5] = mean(data$error1)
  error2all[i,5] = mean(data$error2)
  error3all[i,5] = mean(data$error3)
  testerrorall[i,5] = mean(data$testerror)
  timecostall[i,5] = mean(data$timerecord)
}


error1all[6,3] = -Inf
error2all[6,3] = -Inf
error3all[6,3] = -Inf
testerrorall[6,3] = -Inf
timecostall[6,3] = 10^9

linewidth = 2.5

pdf(file=sprintf('./plots/error1_sparse_lda.pdf'))
par(mar=c(5, 6.4, 1, 1), mgp=c(3.1, 1, 0), las=0,pty = "s")
plot(log(Nall), error1all[,1], type="o", col="blue", pch="o", lty=1, ylim=c(0,1), ylab=TeX(r'($n^{-1}\cdot||\hat{\beta_\lambda}- \beta_\lambda^*||_1$)'),xlab = "Network size n",cex.main=3, cex.lab=2.2, cex.axis=1.8,lwd = 2,cex = 2.5,xaxt = "n")
points(log(Nall), error1all[,4], col="black",pch="o", cex =linewidth)
lines(log(Nall), error1all[,4], col="black", lty=1,lwd = 2)
points(log(Nall), error1all[,5], col="purple",pch="o", cex =linewidth)
lines(log(Nall), error1all[,5], col="purple", lty=1,lwd = 2)
points(log(Nall), error1all[,2], col="red", pch="*", cex = linewidth)
lines(log(Nall), error1all[,2], col="red",lty=2,lwd = 2)
points(log(Nall), error1all[,3], col="dark red",pch="+", cex =linewidth)
lines(log(Nall), error1all[,3], col="dark red", lty=3,lwd = 2)
labels = c("Our method $\\lambda = 1$","Our method $\\lambda = 5$", "Our method $\\lambda = nlogn$", "Stein and Leng (2020)", "Chen et al. (2021)")
legend("topleft",legend=TeX(labels), col=c("blue","black","purple","red","dark red"),pch=c("o","o","o","*","+"),lty=c(1,1,1,2,3), ncol=1, cex = 1.8)
axis(1, at=log(Nall), labels=Nall, cex.axis=1.5)
dev.off()


pdf(file=sprintf('./plots/plots/error2_sparse_lda.pdf'))
par(mar=c(5, 6.4, 1, 1), mgp=c(3.1, 1, 0), las=0,pty = "s")
plot(log(Nall), error2all[,1], type="o", col="blue", pch="o", lty=1, ylim=c(0, 1.1), ylab=TeX(r'($n^{-1/2}\cdot||\hat{\beta_\lambda}- \beta_\lambda^*||_2$)'), xlab = "Network size n" ,cex.main=3, cex.lab=2.2, cex.axis=1.8,lwd = 2,cex = 2.5,xaxt = "n")
points(log(Nall), error2all[,4], col="black",pch="o", cex = linewidth)
lines(log(Nall), error2all[,4], col="black", lty=1,lwd = 2.5)
points(log(Nall), error2all[,5], col="purple",pch="o", cex =linewidth)
lines(log(Nall), error2all[,5], col="purple", lty=1,lwd = 2.5)
points(log(Nall), error2all[,2], col="red", pch="*", cex = linewidth)
lines(log(Nall), error2all[,2], col="red",lty=2,lwd = 2.5)
points(log(Nall), error2all[,3], col="dark red",pch="+", cex =linewidth)
lines(log(Nall), error2all[,3], col="dark red", lty=3,lwd = 2.5)
labels = c("our method $\\lambda = 1$","$\\lambda = 5$", "$\\lambda = nlogn$", "SL", "CKL")
axis(1, at=log(Nall), labels=Nall, cex.axis=1.5)
dev.off()


pdf(file=sprintf('./plots/error3_sparse_lda.pdf'))
par(mar=c(5, 6.4, 1, 1), mgp=c(3.1, 1, 0), las=0,pty = "s")
plot(log(Nall), error3all[,1], type="o", col="blue", pch="o", lty=1, ylim=c(0,3), ylab=TeX(r'($||\hat{\beta_\lambda}- \beta_\lambda^*||_\infty$)') ,cex.main=3, cex.lab=2.2, cex.axis=1.5,lwd = 1.8,cex = linewidth, xlab = "Network size n",xaxt = "n")
points(log(Nall), error3all[,4], col="black",pch="o", cex =linewidth)
lines(log(Nall), error3all[,4], col="black", lty=1,lwd = 2)
points(log(Nall), error3all[,5], col="purple",pch="o", cex =linewidth)
lines(log(Nall), error3all[,5], col="purple", lty=1,lwd = 2)
points(log(Nall), error3all[,2], col="red", pch="*", cex = linewidth)
lines(log(Nall), error3all[,2], col="red",lty=2,lwd = 2)
points(log(Nall), error3all[,3], col="dark red",pch="+", cex =linewidth)
lines(log(Nall), error3all[,3], col="dark red", lty=3,lwd = 2)
labels = c("our method $\\lambda = 1$","$\\lambda = 5$", "$\\lambda = nlogn$", "SL", "CKL")
axis(1, at=log(Nall), labels=Nall, cex.axis=1.5)
dev.off()

pdf(file=sprintf('./plots/testerror_sparse_lda.pdf'))
par(mar=c(5, 6.4, 1, 1), mgp=c(3.1, 1, 0), las=0,pty = "s")
plot(log(Nall), testerrorall[,1], type="o", col="blue", pch="o", lty=1, ylim=c(0,0.15), ylab="Err. of active set Est." ,cex.main=3, cex.lab=2.2, cex.axis=1.8,lwd = 2,cex = 2.5, xlab = "Network size n",xaxt = "n")
points(log(Nall), testerrorall[,4], col="black",pch="o", cex =linewidth)
lines(log(Nall), testerrorall[,4], col="black", lty=1,lwd = 2)
points(log(Nall), testerrorall[,5], col="purple",pch="o", cex =linewidth)
lines(log(Nall), testerrorall[,5], col="purple", lty=1,lwd = 2)
points(log(Nall), testerrorall[,2], col="red", pch="*", cex = linewidth)
lines(log(Nall), testerrorall[,2], col="red",lty=2,lwd = 2)
points(log(Nall), testerrorall[,3], col="dark red",pch="+", cex =linewidth)
lines(log(Nall), testerrorall[,3], col="dark red", lty=3,lwd = 2)
labels = c("our method $\\lambda = 1$","$\\lambda = 5$", "$\\lambda = nlogn$", "SL", "CKL")
axis(1, at=log(Nall), labels=Nall, cex.axis=1.5)
dev.off()


pdf(file=sprintf('./plots/timecost_sparse_lda.pdf'))
par(mar=c(5, 6.4, 1, 1), mgp=c(3.1, 1, 0), las=0,pty = "s")
timecostall = log(timecostall)
timecostall[6,3] = NaN
plot(log(Nall), timecostall[,1], type="o", col="blue", pch="o", lty=1, ylim=c(-5,10), ylab="Log(time)" ,cex.main=3, cex.lab=2.2, cex.axis=1.8,lwd = 2,cex = 2.5, xlab = "Network size n",xaxt = "n")
points(log(Nall), timecostall[,4], col="black",pch="o", cex =linewidth)
lines(log(Nall), timecostall[,4], col="black", lty=1,lwd = 2)
points(log(Nall), timecostall[,5], col="purple",pch="o", cex =linewidth)
lines(log(Nall), timecostall[,5], col="purple", lty=1,lwd = 2)
points(log(Nall), timecostall[,2], col="red", pch="*", cex = linewidth)
lines(log(Nall), timecostall[,2], col="red",lty=2,lwd = 2)
points(log(Nall), timecostall[,3], col="dark red",pch="+", cex =linewidth)
lines(log(Nall), timecostall[,3], col="dark red", lty=3,lwd = 2)
lines(log(Nall), rep(6.761573,length(Nall)), col="dark green", lty=2,lwd = 2)
text(log(500), 7.2, "Total running time = 24 hours", cex = 1.8, col = "dark green")
labels = c("our method $\\lambda = 1$","$\\lambda = 5$", "$\\lambda = nlogn$", "SL", "CKL")
axis(1, at=log(Nall), labels=Nall, cex.axis=1.5)
dev.off()